const {chromium}=require(process.env.PLAYWRIGHT_PATH||'/tmp/bubbles-qa/node_modules/playwright');const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox']});const base=process.env.GAME_URL||'http://127.0.0.1:8000';const errors=[];
async function open(extra='',opts={}){const p=await browser.newPage({viewport:{width:1280,height:720},...opts});p.on('pageerror',e=>errors.push(e.message));if(extra)await p.route('**/config.js',async r=>{const res=await r.fetch();await r.fulfill({response:res,body:await res.text()+'\n'+extra});});await p.goto(base);await p.getByRole('button',{name:'Играть',exact:true}).click();return p;}
const p=await open();await p.waitForTimeout(3500);const geo=await p.locator('button.bubble').evaluateAll(es=>es.map(e=>{const r=e.getBoundingClientRect();return {x:r.x+r.width/2,y:r.y+r.height/2,r:r.width/2};}));for(let i=0;i<geo.length;i++)for(let j=i+1;j<geo.length;j++){const a=geo[i],b=geo[j];assert(Math.hypot(a.x-b.x,a.y-b.y)>=a.r+b.r-1,'circle overlap');}
await p.screenshot({path:'/tmp/bubbles-physics.png'});
const first=p.locator('button.bubble').first(),rect=await first.boundingBox();await p.mouse.move(rect.x+rect.width/2,rect.y+rect.height/2);await p.mouse.down();await p.mouse.move(640,220,{steps:8});assert.equal(await p.locator('.dragging').count(),1);assert.equal(await p.locator('#ghost').isVisible(),false);await first.dispatchEvent('pointercancel');assert.equal(await p.locator('#ghost').isVisible(),false);await p.mouse.up();assert.equal(await p.locator('button.bubble').count(),16);
// Empty-field drop and resize during a drag preserve all words.
await p.mouse.move(rect.x+rect.width/2,rect.y+rect.height/2);await p.mouse.down();await p.mouse.move(640,220,{steps:8});await p.mouse.up();assert.equal(await p.locator('button.bubble').count(),16);
await p.locator('#rules').click();await p.getByRole('button',{name:'Продолжить',exact:true}).press('Tab');assert.equal(await p.evaluate(()=>document.activeElement.closest('dialog')!==null),true);await p.keyboard.press('Escape');assert.equal(await p.locator('#modal').isVisible(),false);await p.close();
const bonus=await open('window.GAME_CONFIG.moveLimit=20;', {reducedMotion:'reduce'});const find=t=>bonus.locator('button.bubble').filter({has:bonus.locator('span',{hasText:new RegExp('^'+t+'$')})});for(const [a,b] of [['ЯБЛОКО','ГРУША'],['БАНАН','ЛИМОН'],['ЯБЛОКО','БАНАН'],['МОРКОВЬ','ОГУРЕЦ'],['МОРКОВЬ','ПОМИДОР']]){await find(a).press('Enter');await find(b).press('Enter');await bonus.waitForTimeout(100);}assert.equal(await bonus.locator('#moves').innerText(),'Ходы: 16');await bonus.locator('#undo').click();assert.equal(await bonus.locator('#moves').innerText(),'Ходы: 16');await bonus.close();
const image=await open("window.GAME_CONFIG.mode='image-word';window.GAME_CONFIG.groups[0].words[0].image='./missing.png';");await image.waitForTimeout(150);assert.equal(await image.locator('img').count(),0);assert.equal(await image.getByRole('button',{name:'ЯБЛОКО. 1 из 4',exact:true}).count(),1);await image.close();
const local=await browser.newPage();try{await local.goto('file:///workspace/puziri/index.html');await local.getByRole('button',{name:'Играть',exact:true}).click();assert.equal(await local.locator('button.bubble').count(),16);}catch(e){if(!String(e).includes('ERR_BLOCKED_BY_ADMINISTRATOR'))throw e;console.log('SKIP: file:// navigation blocked by environment browser policy');}await local.close();
const frame=await browser.newPage({viewport:{width:1400,height:850},reducedMotion:'reduce'});await frame.setContent(`<iframe src="${base}" style="width:1280px;height:720px;border:0" allow="fullscreen"></iframe>`);const f=frame.frameLocator('iframe');await f.getByRole('button',{name:'Играть',exact:true}).click();const a=await f.getByRole('button',{name:'ЯБЛОКО. 1 из 4',exact:true}).boundingBox(),b=await f.getByRole('button',{name:'ГРУША. 1 из 4',exact:true}).boundingBox();await frame.mouse.move(a.x+a.width/2,a.y+a.height/2);await frame.mouse.down();await frame.mouse.move(b.x+b.width/2,b.y+b.height/2,{steps:10});await frame.mouse.up();await frame.waitForTimeout(500);assert.equal(await f.locator('button.bubble').count(),15);await frame.close();
const bad=await browser.newPage();await bad.route('**/config.js',async r=>{const res=await r.fetch();await r.fulfill({response:res,body:await res.text()+'\nwindow.GAME_CONFIG.groups[0].words[0].id=window.GAME_CONFIG.groups[1].words[0].id;'});});await bad.goto(base);assert.equal(await bad.locator('#modal-title').innerText(),'Ошибка конфигурации');await bad.close();
assert.deepEqual(errors,[]);await browser.close();console.log('PASS: normal physics/no overlaps, pointercancel, empty drop, modal focus/Escape, fifth-move bonus, missing image fallback, iframe drag, invalid config.');})().catch(e=>{console.error(e);process.exit(1)});
