const {chromium}=require(process.env.PLAYWRIGHT_PATH||'/tmp/bubbles-qa/node_modules/playwright');const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox']});const p=await browser.newPage({viewport:{width:1280,height:720},reducedMotion:'reduce'}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(process.env.GAME_URL||'http://127.0.0.1:8000');await p.getByRole('button',{name:'Играть',exact:true}).click();const groups=await p.evaluate(()=>window.GAME_CONFIG.groups),find=text=>p.locator('button.bubble').filter({has:p.locator('span',{hasText:new RegExp('^'+text+'$')})});
for(const g of groups){for(const w of g.words.slice(1)){await find(g.words[0].text).press('Enter');await find(w.text).press('Enter');await p.waitForTimeout(100);}await p.waitForTimeout(420);}
assert.equal(await p.locator('#win-scene').isVisible(),true);assert.equal(await p.locator('#modal').isVisible(),false);assert.equal(await p.locator('.mermaid-tail').count(),1);await p.screenshot({path:'/tmp/mermaid-victory-still.png'});
await p.locator('#win-undo').click();assert.equal(await p.locator('#win-scene').isVisible(),false);assert.equal(await p.locator('button.bubble').count(),2);
await p.emulateMedia({reducedMotion:'no-preference'});const g=groups.at(-1);await find(g.words[0].text).press('Enter');await find(g.words.at(-1).text).press('Enter');await p.waitForTimeout(2250);assert.equal(await p.locator('#win-scene').isVisible(),true);
const position=()=>p.locator('#mermaid-swimmer').evaluate(e=>e.getBoundingClientRect().x);const entry=await position();await p.waitForTimeout(1900);const center=await position();assert(center>entry+50,'Mermaid did not swim in');
const arm=()=>p.locator('.mermaid-wave').evaluate(e=>getComputedStyle(e).transform);const tail=()=>p.locator('.mermaid-tail').evaluate(e=>getComputedStyle(e).transform);const firstArm=await arm(),firstTail=await tail();await p.waitForTimeout(550);assert.notEqual(await arm(),firstArm);assert.notEqual(await tail(),firstTail);await p.screenshot({path:'/tmp/mermaid-victory.png'});
await p.waitForTimeout(5900);assert.equal(await p.locator('#win-scene').evaluate(e=>e.classList.contains('finished')),true);assert.equal(await p.locator('#mermaid-swimmer').evaluate(e=>getComputedStyle(e).visibility),'hidden');assert.equal(await p.locator('#play-again').isVisible(),true);await p.locator('#play-again').click();assert.equal(await p.locator('button.bubble').count(),20);assert.equal(await p.locator('#win-scene').isVisible(),false);
assert.deepEqual(errors,[]);await browser.close();console.log('PASS: mermaid instead of card, reduced-motion, swim in, tail/hand animation, swim out, undo victory, replay, no JS errors.');})().catch(e=>{console.error(e);process.exit(1)});
